### ISSUE TITLE
TypoScript Condition Syntax Deprication Warning

### ISSUE THREAD

**Issue by claussni** [slub/slub_web_qucosa#67]
https://github.com/slub/slub_web_qucosa/blob/d1552cc96d7c1040c62a0143a12f9eb68bd730f2/Configuration/TypoScript/Common/setup.typoscript#L308

Fix : https://blog.blue-side.de/2018/10/globalvar-gpl-1-mit-typo3-9-und-sitehandling/

**Comment by Erikmitk** [comment]
Fixed in [master](https://github.com/slub/slub_web_qucosa/commit/bfe83791e4389bdf8cef197d34472178c4c071d3) and [ubl-branch](https://github.com/slub/slub_web_qucosa/commit/7364a7d24058a8ffee42846aac0c951cb6e54c65) ✅
